version:  "3.9"

services:
  spring-boot-app:
    image: spring-kanban-app
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile-spring
    ports:
      - "91:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kanban
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
  frontend:
    image: angular-kanban-app
    container_name: kanban-ui
    build:
      context: src/main/kanbanSystem-front/front-web/kanban-web
      dockerfile: Dockerfile-angular
    ports:
      - "4200:91"
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: kanban
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"

volumes:
  dbdata:
