version: '3'

services:
  spring-boot-app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "91:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kanban
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""


  angular-app:
    container_name: angular-app
    build:
      context: .
    ports:
      - "4200:4500"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kanban
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""


  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: kanban
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"

volumes:
  dbdata:
